# SITE CONFIGURATION
baseurl: ''
url: "https://yoursite.github.io"   #change this to yours ('')
title: My name or organisation # site's title
description: "A website with blog posts and pages" # used by search engines

# SITE-SPECIFIC CONFIGURATION
# Change these 2 images for your own site

avatar: assets/img/face.jpg
favicon: assets/favicon.ico

# Header and footer text
# Change this text to yourown
header_text: Me and my blog

# find an image for your own home page and put it into the images folder
header_feature_image: /images/hhh.jpg
twitter_username: puboxford  #change to your own twitter account
lang: en_gb
# change the following to your name or site name
footer_text:
    "Copyright 2019 My name"
  # Icons
  # If you have any of these accounst add them in here
rss: false  # Make sure you created a feed.xml with feed.xml layout
email_address: # Full email address, e.g. "sam@example.com"
facebook:
flickr:
google_plus:
instagram:
linkedin:  # Full URL
pinterest:
soundcloud:
twitter: # "twitter username"
youtube:

# Sharing options
share_buttons:
  facebook: true
  twitter: true
  tumblr:
  pinterest:
  linkedin:
  email: true

# Scripts / Features
google_analytics: # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:

# Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_share_on: "Share on"
str_add_to: "Add to"
str_email: "Email"
str_tweet: "Tweet"
str_pin_it: "Pin it"
str_next_post: "Next post"
str_previous_post: "Previous post"
str_next_page: "Next"
str_previous_page: "Prev"
str_javascript_required_disqus: "Please enable JavaScript to view comments."

# Post navigation
post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "README.md"]

# You can also use prose (prose.io) to edit and post to your site
prose:
  #rooturl: '_posts'
  siteurl: 'https://yoursite.github.io'
  media: 'images'
  ignore:
    - README.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - _mdwriter.cson
    - .Gemfile.lock
    - .gitignore
    - feed.xml
    - gemfile
    - index.html
    - /assets
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: false
      - name: "header_feature_image"
        field:
          element: "text"
          label: "Optional feature image for the post"
          help: "Paste the URL of the image here"
      - name: "caption"
        field:
          element: "text"
          label: "caption in here"
          help: "add a caption to the image"
      - name: "date"
        field:
          element: "text"
          label: "date"
          help: "current date and time"
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Categories"
          options:
            - name: "InDesign"
              value: "InDsign"
            - name: "HTML"
              value: "HTML"
            - name: "CSS"
              value: "CSS"
            - name: "Typography"
              value: "Typography"
            - name: "Using GitHub"
              value: "Using GitHub"
    pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "published or not"
          value: false
      - name: "image"
        field:
          element: "text"
          label: "Optional feature image for the page"
          help: "Paste the URL of the image here"
      - name: "caption"
        field:
          element: "text"
          label: "caption in here"
          help: "add a caption to the image"
      - name: "date"
        field:
          element: "text"
          label: "date"
          help: "current date and time"
          value: CURRENT_DATETIME
